Added apparmor profile Added bash autocompletion Added unit test to package field extraction Added support for apt reinstall log event parsing Changed github release build script to auto-detect pre-release versions based on version number Fixed bug where packages that had no version would cause program crash (fixed by only extracting version for present fields) Fixed bug where package removal would not disable systemd service start-on-boot (fixed by moving unit disable to prerm script) Fixed bug where excessively large apt operations would become truncated in journald (fixed by chunking package array lists into multiple logs while keeping the same event ID) Fixed bug where installations after state file had been removed would fail to recreate (fixed by ensuring state file parent directory is owned by runas user) Removed dashes from JSON key names for better compatibility with shell-based JSON parsing

diff --git a/packaging/DEBIAN/postinst b/packaging/DEBIAN/postinst
--- a/packaging/DEBIAN/postinst
+++ b/packaging/DEBIAN/postinst
@@ -1,9 +1,16 @@
 #!/bin/bash
 
+# Load apparmor profile
+apparmor_parser -r /etc/apparmor.d/usr.bin.apthl
+if [[ $? != 0 ]]
+then
+	echo "Warning: failed to load apparmor profile"
+fi
+
 # Ensure service starts OK
 serviceName="apthl.service"
 enableStatus=$(systemctl is-active $serviceName)
-if [[ $enableStatus == inactive ]]
+if [[ $enableStatus != active ]]
 then
 	systemctl start $serviceName
 	if [[ $? != 0 ]]
diff --git a/packaging/DEBIAN/postrm b/packaging/DEBIAN/postrm
--- a/packaging/DEBIAN/postrm
+++ b/packaging/DEBIAN/postrm
@@ -17,18 +17,6 @@ then
 	fi
 fi
 
-# Ensure service is disable on removals
-serviceName="apthl.service"
-enableStatus=$(systemctl is-enabled $serviceName 2>/dev/null)
-if [[ $enableStatus == enabled ]]
-then
-	systemctl disable $serviceName
-	if [[ $? != 0 ]]
-	then
-		echo "Warning: failed to disable systemd service $serviceName"
-	fi
-fi
-
 # Cleanup systemd /lib
 serviceUnitFile="/lib/systemd/system/apthl.service"
 if [[ -f $serviceUnitFile ]]
@@ -38,6 +26,13 @@ then
 	then
 		echo "Warning: failed to remove systemd unit file $serviceUnitFile"
 	fi
+fi
+
+# Reload systemd
+systemctl daemon-reload
+if [[ $? != 0 ]]
+then
+	echo "Warning: failed to reload systemd daemons"
 fi
 
 exit 0
diff --git a/packaging/DEBIAN/preinst b/packaging/DEBIAN/preinst
--- a/packaging/DEBIAN/preinst
+++ b/packaging/DEBIAN/preinst
@@ -40,6 +40,14 @@ then
 	exit 1
 fi
 
+chown $stateOwner:root ${stateDirectory}
+if [[ $? != 0 ]]
+then
+	echo "Failed to change state directory ownership for $stateFile" >&2
+	exit 1
+fi
+
+
 chown $stateOwner:root ${stateFile}
 if [[ $? != 0 ]]
 then
